### ISSUE TITLE
How to get VIEW count and SAVE count?

### ISSUE THREAD

**Issue by exislow** [tejado/ebk-client#10]
So the Kleinanzeigen website as well as the app show next to the ad the view count of the ad and also the count of how many times people saved the ad to their bucket list. But I cannot see this values querying the my ads (`https://api.ebay-kleinanzeigen.de/api/users/EMAIL/ads.json`) or a specific ad (`https://api.ebay-kleinanzeigen.de/api/ads/ADID.json`).

Does anybody know how I can retrieve these counters?

Edit:
I have reversed the app code further and found this API `https://api.ebay-kleinanzeigen.de/api/v2/counters/ads/vip/ADID.json` to retrieve the view count.

```
{
    "adId": "ADID",
    "value": 33
}
```

SAVE aka watchlist count can be retrieved using this API `https://api.ebay-kleinanzeigen.de/api/v2/counters/ads/watchlist?adIds=ADID`

```
{
    "counters": [
        {
            "adId": "ADID",
            "value": 3
        }
    ]
}
```

**Comment by exislow** [comment]
Anyway... Solved my problem by myself. You are free to extend your implementation :-)

**Comment by tejado** [comment]
@exislow it would be awesome if you can add your findings over a PR to the code :) would that be possible?

**Comment by exislow** [comment]
Done. See #11. Feel free to review, change and merge the code.
