### ISSUE TITLE
JavaScript (JS) port of the ebk-client

### ISSUE THREAD

**Issue by exislow** [tejado/ebk-client#12]
I have ported the Python code to JS. You can find the library here: https://github.com/exislow/kleinanzeigen-magic/blob/v0.4.2/src-electron/main-process/kleinanzeigen.js

Btw... An Electron app is wrapped around, which gives you a decent GUI.

**Comment by tejado** [comment]
I like that but a backlink + credits would be nice as you mentioned you ported it. Thank you!
