### ISSUE TITLE
Question about Login-Data

### ISSUE THREAD

**Issue by mx02584** [tejado/ebk-client#13]
Hi,

i am unable to enter the correct username and password form.
Always get the message:
```
raise AttributeError(f'Access Denied {r.status_code}') AttributeError: Access Denied 401
```
`api = EbkClient('123@web.de', 'password123', '123@web.de', 'password123')` 

Whats wrong?

**Comment by tejado** [comment]
Please read the README carefully. The first app username and password are different than the second on for the eBay Classifieds user:
api = EbkClient('app-username', 'app-password', 'ebay-user-name', 'ebay-user-password')

Getting the first username and password needs a partner API account of the platform. An alternative is, to get these from the Android app, described here (and also linked in the readme....): https://euer.krebsco.de/finding-the-ebay-kleinanzeigen-application-password.html
