### ISSUE TITLE
Login procedure has changed

### ISSUE THREAD

**Issue by exislow** [tejado/ebk-client#14]
Your code is not working anymore, since you need to acquire a token first to be able to send any requests to the API.  The solution is documented here: https://github.com/exislow/kleinanzeigen-magic/issues/12

Btw... In the next push I will refer to this repository in my README.md. Maybe you want also to refer to my implementation of this python library :-)

**Comment by tejado** [comment]
Thanks a lot @exislow for creating the issue and providing a fix for it.
And @felixb thanks a lot for merging this to ebk-client!

I really appreciate your contributions.

**Comment by exislow** [comment]
You are very welcome. It seems more and more changes will be implemented by the new owner of Kleinanzeigen in the next couple of years. I have read that eBay gave the new owner a two year grace period to rebrand their app. The whole backend will be moved to the dutch owner's infrastructure.

**Comment by tejado** [comment]
Interessting. Thanks for the heads-up. I hope the general platform will not be changed in a negative way... If they change their backend, it is fine for me: I'm not using any 3rd party clients (like ebk-client) anymore.
