### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by johann929292** [tejado/ebk-client#17]
Thanks

**Comment by tejado** [comment]
Hi Johann, what do you mean with "access"? The source is already here on github and everything is described in the readme...

**Comment by johann929292** [comment]
Hello Thanks for the answer! Oh, so i need to be a special Partner to use the API Library? Didnt work for me with my App and Account Logins

**Comment by tejado** [comment]
Please have a look into the readme and follow carefully all links:

_The smartphone apps (e.g. for Android) must include also some static/hardcoded partner account as it is using the same API (further information on this can be found [here](https://euer.krebsco.de/finding-the-ebay-kleinanzeigen-application-password.html))._

**Comment by johann929292** [comment]
Thanks again for the fast reply, thats what im trying, but i get always this error here...
dex2jar ./classes.dex -> .\classes-dex2jar.jar
Detail Error Information in File .\classes-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
