### ISSUE TITLE
correct credentials?

### ISSUE THREAD

**Issue by anzgar01** [tejado/ebk-client#4]
Hi there,
I am new to python and ebk, so sorry for the stupid question, but which are the correct credentials to use with the example.py?
app-username = eBay Kleinanzeigen Username? Or is it the ebay developer username?
ebay-username = ebay username, or is it ebay kleinanzeigen username?

Sorry for asking, but I just don't know where to put which credentials.

I always geht access denied when trying the example.

Thanks a lot in advance!!

**Comment by tejado** [comment]
Hi anzgar01,

welcome to github :)
So, the app-username and password are special eBay Kleinanzeigen credentials which they are using to protect the API. I assume that these are given out for partner customers but of course, their mobile app uses also this API and therefor needs such an account. For further information please have a look here: https://github.com/tejado/ebk-client/issues/2

The ebay-username and password are credentials of your normal eBay kleinanzeigen account.

I hope this helps a little.

Best regards!

**Comment by makefu** [comment]
I've written a short blog post on how to find the api credentials: https://euer.krebsco.de/finding-the-ebay-kleinanzeigen-application-password.html

**Comment by tejado** [comment]
Great, thank you! If you don't mind, I will add it to the readme.

By the way: 
There are also online Java APK decompilers if you don't want to download one just for this purpose.
