### ISSUE TITLE
XML creation / quoting

### ISSUE THREAD

**Issue by felixb** [tejado/ebk-client#5]
Hi there,

I'm trying to create an ad with your library. Basic XML creation works and I can post new ads with boilerplate text.

I'm trying to post an ad with `ä` in the title with following variations:
1. No escaping at all: `<ad:title>foo bär</ad:title>`
2. HTML escaping: `<ad:title>foo b&auml;r</ad:title>`
3. Double HTML escaping: `<ad:title>foo b&amp;auml;</ad:title>`

1 and 2 fail with
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<api-base-error xmlns="http://www.ebayclassifiedsgroup.com/schema/types/v1" http-status-code="400">
    <api-errors>
        <api-error>
            <message>Cannot unmarshal content</message>
        </api-error>
    </api-errors>
    <api-debug-errors/>
    <api-field-errors/>
</api-base-error>
```
3 creates the ad, but the title is `foo b&auml;r`

Do you have any suggestions?

**Comment by felixb** [comment]
The way to do it is:
No escaping + encoding the whole XML content explicitly with `utf-8` like this:

```python
    def create_ad(self, xml):
        url = "/users/{}/ads.json".format(self.username)
        response = self._http_post(url, xml.encode('utf-8'))
        return response
```

**Comment by tejado** [comment]
Hey Felix,

thanks for the hint. Feel free to PR this. Otherwise I will add it later.

OT: nice to see someone from Hamburg and from OTTO here on github ;-)

**Comment by felixb** [comment]
I'll send a PR when done with all the other stuff I need for my client.
I'm not with OTTO anymore though. ;)

**Comment by tejado** [comment]
I guess this is resolved then :-)
