### ISSUE TITLE
Mark conversation as read

### ISSUE THREAD

**Issue by Smalakamp** [tejado/ebk-client#7]
Hi,

by using the ebay-kleinanzeigen-api i can read conversations without problem.
My only problem is to mark messages as read. The messages are not set as read by just reading it.

Any solutions?

Regards

**Comment by tejado** [comment]
I searched a little bit and found a PUT request on the path '/api/users/{userId}/notifications/{notificationId}/read'. Can you try if this is working?

**Comment by Smalakamp** [comment]
works fine, can you share the link where you found this solution?

**Comment by tejado** [comment]
there is no link to share about this. Seems the eBay API specification does not mention this. But you can check what calls the app is doing, e.g. by mitm the network traffic.
